from . import student_application
from . import week_days
from . import student
from . import department
from . import subject
from . import subject_level
from . import course
from . import course_session
from . import enrollment
from . import attendance
from . import payment_line
from . import student_portal