{
    'name': 'Student Application Form',
    'version': '1.0',
    'summary': 'Module for student registration form',
    'description': 'A custom module for managing student applications and exporting to PDF.',
    'author': 'Ahmed Labib',
    'depends': ['base', 'web', 'product', 'account', 'portal', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/week_days_data.xml',
        #'data/departments_data.xml',
        'views/student_application_view.xml',
        'views/student_view.xml',
        'views/department_view.xml',
        'views/course_session_view.xml',
        'views/payment_line_view.xml',
        'views/subject_view.xml',
        'views/course_view.xml',
        'views/enrollment_view.xml',
        'views/portal_templates.xml',
        'views/student_portal_view.xml',
        'report/application_print.xml',
        'report/ir_actions_report.xml',
        'report/layout.xml',
    ],
    'installable': True,
    'application': True,
}